name: MAMnet
channels:
        - defaults
        - bioconda
        - conda-forge
dependencies:
        - python==3.9
        - anaconda
        - pip
        - pip:
          - -r file:requirements.txt
